name: Build VST3 macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mac:
    runs-on: macos-14

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure
      run: |
        cmake -B build -G Xcode \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
    - name: Configurare CMake
      run: |
        rm -rf build
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DJUCE_BUILD_EXTRAS=OFF
   
    - name: Compilare il Plugin
      run: |
        cmake --build build --config Release --parallel 4

    - name: Architettare il file VST3
      run: |
        # Usiamo il path standard generato da JUCE usando il Product Name
        cd build/MicrotonalAutotune_artefacts/Release/VST3
        zip -r ../../../../MicrotonalAutotune_Mac_VST3.zip ./*

    - name: Caricare l'Artefatto su GitHub
      uses: actions/upload-artifact@v4
      with:
        name: MicrotonalAutotune-macOS-VST3
        path: MicrotonalAutotune_Mac_VST3.zip
